In [1]:
import numpy as np

# Problem 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [2]:
multiples = np.array([i for i in range(1000) if i%3==0 or i%5==0])
multiples.sum()

233168

# Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [6]:
fib_nums = [1, 2]
prev2 = fib_nums[-1] + fib_nums[-2]
even_sum = 2
while prev2 <= 4000000:
    fib_nums.append(prev2)
    prev2 = fib_nums[-1] + fib_nums[-2]
    if prev2 % 2 == 0:
        even_sum += prev2
even_sum

4613732

In [8]:
fn = [1, 2]
while fn[-1] < 4000000:
    fn.append(sum(fn[-2:]))

even_fn = [i for i in fn if i%2==0]
sum(even_fn)

4613732

# Problem 3
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [28]:
def is_prime(n):
    if n == 2 or n == 3: return True
    if n < 2 or n%2 == 0: return False
    if n < 9: return True
    if n%3 == 0: return False
    r = int(n**0.5)
    f = 5
    while f <= r:
        if n%f == 0: return False
        if n%(f+2) == 0: return False
        f +=6
    return True

def max_prime_factor(n):
    for i in range(int(n**.5), 2, -1):
        if n%i == 0 and is_prime(i):
            return i
    print('no prime factors')

In [33]:
max_prime_factor(600851475143)

6857

# Problem 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [62]:
def is_palindrome(n):
    x = list(str(n))
    x.reverse()
    rev = int(''.join(x))
    return n == rev


def largest_palindrome(n):
    products = [i*j for i in range(n) for j in range(n)]
    products.sort(reverse=True)
    for product in products:
        if is_palindrome(product):
            return product

In [63]:
largest_palindrome(999)

906609

# Problem 5
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [65]:
import math

In [91]:
from functools import reduce

def gcd(a, b):
    """Return greatest common divisor using Euclid's Algorithm."""
    while b:      
        a, b = b, a % b
    return a

def lcm(a, b):
    """Return lowest common multiple."""
    return a * b // gcd(a, b)

def lcmm(args):
    """Return lcm of args."""   
    return reduce(lcm, args)

In [92]:
lcmm(list(range(1,21)))

232792560

# Problem 6
The sum of the squares of the first ten natural numbers is,

1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)^2 = 55^2 = 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [93]:
sosq = sum([i**2 for i in range(1, 101)])
sqos = sum(range(1, 101))**2
sqos - sosq

25164150

# Problem 7
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [94]:
def is_prime(n):
    if n == 2 or n == 3: return True
    if n < 2 or n%2 == 0: return False
    if n < 9: return True
    if n%3 == 0: return False
    r = int(n**0.5)
    f = 5
    while f <= r:
        if n%f == 0: return False
        if n%(f+2) == 0: return False
        f +=6
    return True

In [100]:
prime_counter = 0
n = 1
while prime_counter < 10001:
    n += 1
    if is_prime(n):
        prime_counter += 1
n

104743

# Problem 8
The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [101]:
num = 7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450
len(str(num))

1000

In [107]:
nal = [int(i) for i in list(str(num))] # number as list
digits = []
max_prod = 0
for i in range(1000-13):
    prod = reduce(lambda x, y: x*y, nal[i:i+13])
    if  prod > max_prod:
        max_prod = prod
        digits = nal[i:i+13]
    
print(digits, '\n', max_prod)

[5, 5, 7, 6, 6, 8, 9, 6, 6, 4, 8, 9, 5]
 23514624000

# Problem 9
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [112]:
abc = None
for a in range(1,1001):
    if a%100 == 0:
        print(a)
    if abc:
        break
    for b in range(1,1001):
        if abc: 
            break
        for c in range(1,1001):
            if a+b+c == 1000 and a**2+b**2 == c**2:
                abc = [a, b, c]
                break
reduce(lambda x, y: x*y, abc)

100
200

31875000

In [113]:
abc

[200, 375, 425]

# Problem 10
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [ ]:
def is_prime(n):
    if n == 2 or n == 3: return True
    if n < 2 or n%2 == 0: return False
    if n < 9: return True
    if n%3 == 0: return False
    r = int(n**0.5)
    f = 5
    while f <= r:
        if n%f == 0: return False
        if n%(f+2) == 0: return False
        f +=6
    return True

In [114]:
prime_sums = 0
for i in range(2, 2000001):
    if is_prime(i):
        prime_sums += i
        
prime_sums

142913828922